<a href="https://colab.research.google.com/github/pccalegari/Exemplos_ICC/blob/main/unidade5_icc.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>





# Unidade 5 - Estruturas de dados básicas




Até agora estudamos variáveis simples, capazes de armazenar apenas um tipo, como *bool*, *float* e *int*. Nesta unidade, vamos estudar algumas estruturas de dados simples, os **vetores** e as **matrizes**, em um contexto geral. Estas estruturas servem para armazenar dados durante a execução do programa. Vamos ver exemplos de aplicação destas estruturas na modelagem e resolução de problemas computacionais. Em seguida, vamos estudar as estruturas de dados da linguagem de programação *Python*, como listas, dicionários, entre outras, para nos auxiliar na implementação de vetores e matrizes.

# Vetores

Vetores são estruturas de dados indexadas usadas para armazenar dados de um mesmo tipo: *int*, *float* e *str*.

O exemplo a seguir apresenta um vetor de números inteiros de tamanho 6, pois possui seis posições. Cada posição é indicada por um índice.


\begin{array}{cccccc}
0 & 1 & \hspace{0.3pc} 2 & 3 & 4 & \hspace{0.3pc} 5\\
\end{array}
\begin{array}{|c|c|c|c|c|c|}
\hline
-1 & 13 & 0 & 3 & 2 &17 \\
\hline
\end{array}

O próximo exemplo apresenta um vetor de números reais (tipo *float*) de tamanho 10. Podemos usar um vetor de números reais para armazenar as notas de uma turma de estudantes.


\begin{array}{cccccccccc}
0 & & 1 & & 2 & & 3 & & 4  & &5 & &  6 & & 7 & & 8 &  9\\
\end{array}
\begin{array}{|c|c|c|c|c|c|c|c|c|c|}
\hline
9.5 & 10.0 & 9.0 & 5.5 & 6.0 & 3.5 & 8.5 & 7.0 & 7.5 & 5  \\
\hline
\end{array}

**Uso de vetores:**



*   Os índices são usados para acessar uma posição do vetor.
*   Um índice é um número inteiro, em algumas linguagens, um número natural.
*   O índice da primeira posição é zero.

Podemos criar um vetor em *Python* usando uma **lista**. O exemplo abaixo apresenta como acessamos a infomação armazenada em uma determinada posição do vetor.


In [ ]:
x = [-1, 13, 0, 3, 2, 17]
notas = [9.5, 10.0, 9.0, 5.5, 6.0, 3.5, 8.5, 7.0, 7.5, 5]

# Acesso para mostrar valor armazenado



# Acesso para alterar um valor armazenado




**Percorrimento de Vetores**

Percorrer um vetor significa passar por todas as posições dele. Para fazer isso, precisamos saber o tamanho (quantidade de posições do vetor).  Em *Python* a função *len()* retorna o tamanho de uma lista, nesse caso, um vetor. Um padrão para percorrer um vetor é utilizar um comando de repetição, como no exemplo a seguir.







In [ ]:
notas = [9.5, 10.0, 9.0, 5.5, 6.0, 3.5, 8.5, 7.0, 7.5, 5]
n = len(notas)
print("Tamanho do vetor x: ", n)
print("Dados armazenados em cada posição de x:")
for i in range(n):
   print("Posição: ", i, "Valor: ", notas[i])


Com a linguagem *Python* podemos usar índice negativos. Índices negativos indicam elementos da direita para a esquerda ao invés de da esquerda para a direita. Mas para cada tamanho de vetor, os índices possuem um limite inferior e superior.  
Um erro comum é acessar uma posição do vetor que não existe, ou seja, ultrapassar os limites inferior e superior. A mensagem de erro quando acessamos um índice inválido é *index out of range*.

No exemplo anterior, podemos acessar os seguintes índices:

\begin{array}{cccccccccc}
-10 & -9 & -8 &  -7  & -6  & -5 & -4 & -3 & -2 & -1 \\
0 &  1 &  2  & 3 &  4   &5  &  6  & 7  & 8 &  9\\
\end{array}
\begin{array}{|c|c|c|c|c|c|c|c|c|c|}
\hline
9.5 & 10.0 & 9.0 & 5.5 & 6.0 & 3.5 & 8.5 & 7.0 & 7.5 & 5  \\
\hline
\end{array}

Experimente incluir no programa acima, uma de cada vez, as linhas:

```
print(x[-1])

print(x[-10])

print(x[10])

print(x[-11])
```

Agora, vamos estenter um pouquinho os conceitos, apresentando as listas.

**Listas**

São estruturas de dados (tipo *list*) de dados sequenciais e indexadas. Uma lista é uma sequência ou coleção de dados de qualquer tipo, *int*, *bool*, *str*, *list*, entre outros. Os elementos da lista são separados por vírgula.

```
x = [-1, 1.2, 'Liz', True, [1, 2]]
```
Podemos criar uma lista vazia.

```
l = []
```
Experimente os comandos acima, incluido

```
m = len(x)
print(len(l))
print(type(x))
for elemento in x:
   print(type(elemento))
```

No comando vemos um uso do comando *for* diferente do que vínhamos usando. Nesse exemplo, **elemento** é a variável do laço de repetição da lista com nome **x**. Dentro do bloco do comando de repetição (corpo do laço) temos a instrução *print(type(elemento))* que vai mostrar o tipo de variável de cada dado armazenado na lista. A cada **iteração** do laço de repetição, um teste verifica se ainda existem itens na lista para serem processados. Se não há mais nenhum item, a repetição termina.

Com estes conceitos iniciais de listas, podemos fazer a leitura de um vetor de qualquer tamanho.

**Leitura de um vetor:**

Para receber um vetor, precisamos ler elemento a elemento, usando o padrão de percorrimento. Para isso, inicialmente criamos uma lista vazia, recebemos o tamanho do vetor, e depois com um comando de repetição fazemos a inicialização elemento a elemento, usando o método *append*. O operador ponto pode ser usado para acessar métodos nativos da linguagem *Python* para listas. O método *append* insere o argumento passado para ele no final de uma lista. Veja o exemplo.

In [ ]:
# Cria lista vazia
x = []
# Recebe o tamanho do vetor
n = int(input("Digite o tamanho do vetor"))
print("Digite ", n, " números inteiros.")
for i in range(n):
   valor = int(input())
   x.append(valor)

print(x)

**Exercícios:**

1.  Escreva uma função que receba dois vetores e devolva a soma destes vetores.
2.  Escreva uma função que calcule o produto escalar de dois vetores.
3.  Escreva uma função receba um vetor e devolva o seu valor máximo (em valor absoluto).
4.  Dados $n>0$ lançamentos de um dado de seis lados, calcule a frequência de cada número.

**Exemplos de problemas com listas:**

1. Escreva uma função que, dada uma lista $l$, devolve uma lista cópia de $l$.

2. Crie uma função que, dadas duas listas $l_1$ e $l_2$, adiciona os elementos de $l_2$ no final de $l_1$.

3.  Escreva uma função que, dada uma lista $l$ e um valor $x$, devolve a primeira posição de $l$ que é igual a x ou devolve -1 se $x$ não está em $l$.

4. Devolva uma função que dada uma lista, devolve uma lista com os elementos na ordem inversa.

In [ ]:
#Exemplo 1
def copia_lista(lista):
  copia = []
  for item in lista:
    copia.append(item)
  return copia

l1 = ['a', 'b', 'c']
l2 = copia_lista(l1)
print(l2)
l1[1] = 'x'
print(l1)

In [ ]:
#Exemplo 2
def concatena(l1, l2):
  z = l1 + l2
  return z

l3 = concatena([1,2,3], [4,5,6])
print(l3)

In [ ]:
#Exemplo 3

def busca(lista, x):
  n = len(lista)
  i = 0
  index = -1
  while (i < n and index == -1):
    if(x == lista[i]):
      index = i

    i = i + 1
  return index

l = [1, 0, 3, 5 , 7]
x = 13

i = busca(l, x)
print(i)

**Outros métodos de listas:**

*  Para fatiar listas

```
l[i:f] # i: indice início e f: índice fim, f-1
l[i:f:p]  # percorre os índices r = i + k*p, k =0,1,...
```

*   Para copiar listas:

```
l2 = l.copy() ou l2 = l[:]
```

Atenção:
```
l2 = l1
```
não faz uma cópia da lista, apenas uma referência.

*   Adiciona listas:

Adiciona os elementos de l2 no fim da lista l1.
```
l1.extend(l2)
```

*   Busca por elemento:

```
l.index(x)  # devolve primeiro índice de l tal que l[i]==x
```

*   Inverte ordem dos elementos:

```
l.reverse()  # inverte a ordem dos elemetos na própria l
```

**Mais exemplos com listas:**

1.   Escreva uma função que dados uma lista l, um índice i e um valor x, insere x na posição i.
2.   Escreva uma função que recebe uma lista e um índice, remove essa posição da lista e devolve o velor removido.
3.   Escreva uma função que dados uma lista l e um valor x, remove a primeira ocorrência de x em  l.



**Strings**

*   São sequências de caracteres, sendo que cada caracter pode ser acessado por índices (como listas).

*   Strings são imutáveis.

*   O método len devolve o tamanho (número de caracteres) da string.

*  O operador booleano in para duas strings, retorna True se a primeira aparecer como parte da segunda.



**Mais alguns métodos para listas:**

*  O método list transforma uma *string* em uma lista de letras.

*  Remoção:

Para remover elementos e um lista por meio do índice podemos usar os métodos pop ou del (nesse perdemos o elemento). Quando sabemos o elemento a ser removido, mas não o índice, podemos usar o remove.

```
s = 'string'
l = list(s)
x = l.pop(1)
del l[1]
```

*   O método split quebra uma *string* (sequência de caracteres) em uma lista de palavras.

*   O método join faz o inverso do método split.

```
l.extend(['a','b','c'])
limitante = ' '
limitante.join(l)
```

**Exemplos**

1. Escreva uma função que receba uma *string* e verifique se ela é um palíndrome.

In [ ]:
s='string'
l = list(s)
print(l)
x = l.pop(0)
del l[2]
print(l)
l.extend(['a','i'])
limitante=''
a = limitante.join(l)
a = a + ' hoje'
print(a)
b = a.split()
print(b)
limitante = ' '
an = limitante.join(b)
print(an)

In [ ]:
a = "socorram me subi no onibus em marrocos" #saudavel leva duas"
b = a.split()
#print(b)
n = len(b)
c = ''
for i in range(n):
    c = c + b[i]


print(c)
i = 0

palin = True
while(i < len(c)//2 and palin):
  if c[i] != c[len(c)-1-i]:
    palin = False
  i += 1
print(palin)


socorrammesubinoonibusemmarrocos
True


**Exercícios:**

1.  Escreva uma função que receba as informações de um estudante, nome, matrícula e três notas e as armazene em uma lista.

2.  Dada uma sequência de $n > 0$ números inteiros, apresentá-los eliminando as repetições.

3.  Dados dois números naturais $m$ e $n$ e duas sequências ordenadas com $m$ e $n$ números inteiros, obter uma única sequência ordenada contendo todos os elementos das sequências originais sem repetição. Sugestão: Imagine uma situação real, por exemplo, dois fichários de uma biblioteca.

4.  Considere uma lista da forma descrita no exercćio 1. Escreva uma função que receba a lista e outros parâmetros que sejam necessários e que devola a média aritmética das notas do estudante.

# Matrizes

São estruturas indexadas (na forma matricial) utilizadas para armazenar dados de um mesmo tipo: inteiro, caracter, real, etc...

$$\begin{array}{|c|c|c|c|c|c|}
\hline
 & & & & & \\
 \hline
 & & & & & \\
 \hline
 & & & & & \\
 \hline
 & & & & & \\
 \hline
 \end{array}$$

Uso de matrizes:

*   São usados índices para acessar uma linha e uma coluna de uma matriz.
*   Os índices dão números naturais.
*   O índice da primeira linha e da primeira coluna é zero.

Erros Comuns:

*   Índices inválidos: tome cuidado para dentro de repetições não acessar índices negativos ou maiores que o tamanho da matriz.
*   Em *Python* podemos criar uma matriz de forma dinâmica uando recursos da estrutura de listas. Mas é preciso ter muito cuidado ao criar matrizes e ter consciência que em outras linguagens de programação a criação de uma matriz é feita de uma forma diferente.

Percorrimento de matrizes:

Muitos problemas computacionais que envolvem matrizes têm como soluções o uso de um padrão para percorrer a matriz. Podemos percorrer uma matriz de diferentes maneiras:
*    Percorrimento de uma linha da matriz.
*    Percorrimento completo da matriz por linhas.
*    Percorrimento de uma coluna da matriz.
*    Percorrimento completo da matriz por colunas
*    Percorrimento da diagonal principal de uma matriz.
*    Percorrimento de diagonal secundária de uma matriz.
*     Entre outras...

*Exemplo 1:*

Vamos utilizar listas para trabalhar com matrizes em *Python*. Vamos criar uma matriz A com 3 linhas e 4 colunas e percorrer seus elementos usando duas repetições.

$$\begin{array}{|c|c|c|c|}
\hline
 1 & 2 & 3 & 4\\
 \hline
 5 & 6 & 7 & 8 \\
 \hline
 9 & 10 & 11  & 12\\
 \hline
 \end{array}$$



In [ ]:
A = [[0, 0, 0, 0], [0, 0, 0, 0], [0, 0, 0, 0]]
print(len(A), len(A[0]))

for i in range(len(A)):
    for j in range(len(A[0])):
        A[i][j] = 1 + j + i*len(A[0])
print(A)

3 4
[[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]]


O módulo numpy do *Python* é uma biblioteca de álgebra linear que facilita o trabalho com matrizes e vetores. Para utilizá-la precisamos usar o comando *import*. Em seguida, temos um exemplo de criação de uma matriz, com m linhas e n colunas e com todos os elemento nulos e depois fazemos a sua inicialização.



In [ ]:
import numpy as np
n = 3
m = 4
A = np.zeros((m,n))
for i in range(m):
    for j in range(n):
        A[i][j] = 1 + j + i*n
print(A)

[[ 1.  2.  3.]
 [ 4.  5.  6.]
 [ 7.  8.  9.]
 [10. 11. 12.]]


**Exemplos**



1.   Escreva um programa que leia o tamanho de uma matriz quadrada e verifique se a matriz possui uma linha, uma coluna ou uma diagonal nula.
2.   Escreva um programa que verifique se uma matriz A é simétrica. Ou seja, $a_{ij}=a_{ji}$.
3. Escreva um programa que receba duas matrizes de mesmo tamanho e calcule a soma dessas matrizes, a soma é feita elemento a elemento.



*Linearização de índices*

Por questões de eficiência podemos armazenar uma matriz em uma lista, no lugar de armazenar em uma lista de listas.

$$\begin{array}{|c|c|c|c|}
\hline
 1 & 2 & 3 & 4\\
 \hline
 5 & 6 & 7 & 8 \\
 \hline
 9 & 10 & 11  & 12\\
 \hline
 \end{array} \Longrightarrow \begin{array}{|c|c|c|c|c|c|c|c|c|c|c|}
\hline
 1 & 2 & 3 & 4 & 5 & 6 & 7 & 8 & 9 & 10 & 11  & 12\\
 \hline
 \end{array}$$

 Precisamos de uma função bijetiva entre cada posição da matriz $(i,j)$ e sua respectiva posição $k$ no vetor.

 No exemplo temos $m=3$ linhas e $n=4$ colunas. Note que devemos ter:

 $$\begin{array}{|c|c||c|c|}
\hline
(i,j) & k & (i,j) & k\\
\hline
 (0,0) & 0 & (1,2) & 6\\
 (0,1) & 1 & (1,3) & 7 \\
  (0,2) & 2 &(2,0)  & 8\\
(0,3) & 3 & (2,1) & 9\\
 (1,0) & 4 & (2,2) & 10 \\
  (1,1) & 5 & (2,3)  & 11\\
 \hline
 \end{array} \Longrightarrow  \begin{array}{|c|c||c|c|}
\hline
(i,j) & k & (i,j) & k\\
\hline
 (0,0) & 0 & (1,2) & 6\\
 (0,1) & 1 & (1,3) & 2n-1 \\
  (0,2) & 2 &(2,0)  & 2n \\
(0,3) & n-1 & (2,1) & 9\\
 (1,0) & n & (2,2) & 10 \\
  (1,1) & n+1 & (2,3)  & m*n-1\\
 \hline
 \end{array}$$

 Assim, temos: $k = i*n+j$. Para retornar, precisamos saber quantas linhas completas formamos, $i = k//n$ e quantas colunas sobraram, $j = k\%n$.

 **Matrizes Multidimensionais**

 Vimos matriz com duas dimensões, contendo linhas e colunas. Dependendo da aplicação poderemos ter matrizes de dimensões maiores.

 Exemplos:

 1.  Uma função com três variáveis, armazenada em uma matriz para ser graficada. Teríamos $f(x_i,y_j,z_k)$ armazenada em $A[i][j][k]$.

 2.  Imagens coloridas que em cada linha e coluna precisamos armazenar três valores, referentes a escala RGB, por exemplo. Nesse caso, para armazenar estes valores teríamos: $A[i][j][k][l][m]$



**Exercícios:**

1.  Escreva uma função que receba uma matriz de tamanho $n\times n$ e devolva o maior elemento em valor absoluto.

2.  Escreva um algoritmo que receba uma matriz $n\times n$ e determine o traço da matriz, ou seja, a soma dos elementos da diagonal principal.

3.  Escreva um algoritmo que receba uma matriz $n\times n$ e determine a quantidade de elementos não nulos que ela possui.

4.  Dado um sistema de equações lineares,

$$\begin{array}{cccccccc}
a_{11}x_1 & + & a_{12}x_2 & + & \ldots & + & a_{1n}x_n & = & b_1,\\
a_{21}x_1 & + & a_{22}x_2 & + & \ldots & + & a_{2n}x_n & = & b_2, \\
\vdots & \ddots & & & & & \vdots & = & \vdots \\
a_{n1}x_1 & + & a_{n2}x_2 & + & \ldots & + & a_{nn}x_n & = & b_n,
\end{array}$$

podemos reescrevê-lo no formato matricial,

$$\left(\begin{array}{cccccccc}
a_{11} & a_{12} & \ldots & a_{1n} \\
a_{21} & a_{22} & \ldots & a_{2n} \\
\vdots & \ddots & & \vdots \\
a_{n1} & a_{n2} & \ldots & a_{nn}
\end{array}\right)\left(\begin{array}{c}
x_1\\
x_2\\
\vdots\\
x_n
\end{array}\right) = \left(\begin{array}{c}
b_1\\
b_2\\
\vdots\\
b_n
\end{array}\right),$$
onde $A=(a_{ij})$ é a matriz de coeficientes e $b$ é o vetor lado direito do sistema, ambos dados do problema. O vetor $x$ é o vetor de incógnitas.

Escreva uma função que dados uma matriz $A$, um vetor $b$ e um vetor de soluções $x$, verifique se $x$ é solução do sistema linear, ou seja, se $Ax=b$.

5.  Agora pesquise nas bibliotecas *numpy* e *scipy* se já existem funções ou métodos que resolvem os exercícios anteriores.

6. Escreva uma função que receba duas matrizes de mesmo tamanho e devolva uma terceira matriz que é a soma das duas. Utilize a linearização de índices.

7. Escreva uma linearização para uma  matriz com três dimensões.